FROM python:3.8-slim-buster
COPY requirements.txt /tmp
WORKDIR /enphase
COPY ./enphase_local.py .
RUN apt-get update
RUN apt-get install build-essential manpages-dev 
RUN python3 -m pip install --no-cache-dir -r /tmp/requirements.txt
CMD ["python3", "enphase_local.py"]